version: "3.7"
volumes:
  database:
services:
  db:
    image: mysql:latest
    container_name: premio-ari-bd
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ar1mprens@
      - MYSQL_DATABASE=premio-ari
      - MYSQL_USER=premio-ari
      - MYSQL_PASSWORD=ar1mprens@